apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-state-metrics
  labels:
    monitoring: prometheus
spec:
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 30s
      honorLabels: true
      relabelings:
        - targetLabel: cluster
          replacement: opendefence
