apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter
  labels:
    monitoring: prometheus
spec:
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/name: node-exporter
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      relabelings:
        - targetLabel: cluster
          replacement: opendefence
