apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
  labels:
    monitoring: prometheus
spec:
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      operated-prometheus: "true"
  endpoints:
    - port: web
      path: /metrics
      interval: 30s
      relabelings:
        - targetLabel: cluster
          replacement: opendefence
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubelet
  labels:
    monitoring: prometheus
spec:
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      k8s-app: kubelet
  endpoints:
    - port: https-metrics
      path: /metrics
      scheme: https
      interval: 30s
      honorLabels: true
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
      relabelings:
        - sourceLabels:
            - __metrics_path__
          targetLabel: metrics_path
        - targetLabel: cluster
          replacement: opendefence
    - port: https-metrics
      path: /metrics/cadvisor
      scheme: https
      interval: 30s
      honorLabels: true
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
      relabelings:
        - sourceLabels:
            - __metrics_path__
          targetLabel: metrics_path
        - targetLabel: cluster
          replacement: opendefence
    - port: https-metrics
      path: /metrics/resource
      scheme: https
      interval: 30s
      honorLabels: true
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
      relabelings:
        - sourceLabels:
            - __metrics_path__
          targetLabel: metrics_path
        - targetLabel: cluster
          replacement: opendefence
