apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.91.0/example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.91.0/example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.91.0/example/rbac/prometheus-operator/prometheus-operator-service-account.yaml
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.91.0/example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.91.0/example/rbac/prometheus-operator/prometheus-operator-service.yaml
