apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: password-32-8digits-no-symbols
spec:
  length: 32
  digits: 8
  symbols: 0
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-password
spec:
  refreshInterval: "0"
  target:
    name: grafana-admin-password
    template:
      type: Opaque
      data:
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: password-32-8digits-no-symbols
